{% set name = "srm-ifce" %}
{% set version = "1.24.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 1acc7da355bdc77a4690d481eb1066a39884035364849bca64792ca02e6e304e
  patches:
    - 0001-Check-_DARWIN_FEATURE_ONLY_64_BIT_INODE-in-gfal_srm_.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, "x.x.x") }}
    # Building with a different gsoap version changes the ABI
    - {{ pin_compatible('gsoap', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - sed
    - gsoap
  host:
    - glib
    - gsoap
    - openssl
    - gct
    - cgsi-gsoap

test:
  commands:
    - gfal_srm_ifce_version

about:
  home: https://dmc.web.cern.ch/projects-tags/srm-ifce
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Storage Resource Manager Interface
  description: |
    srm-ifce is a client side implementation of the
    [SRMv2 specification](https://sdm.lbl.gov/srm-wg/doc/SRM.v2.2.html) for
    GFAL and FTS. SRM means Storage Resource Manager Interface, it is a
    specification of a SOAP interface providing a generic way to manage
    distributed storage systems.
  doc_url: https://dmc-docs.web.cern.ch/dmc-docs/srm-ifce.html
  dev_url: https://gitlab.cern.ch/dmc/srm-ifce

extra:
  recipe-maintainers:
    - chrisburr
